import { Client, ClientStats } from '../types/client';

// Mock client data
export const MOCK_CLIENTS: Client[] = [
  {
    id: '1',
    companyName: 'ABC Construction Corp',
    contactPerson: 'John Smith',
    email: 'info@abcconstruction.com',
    phone: '+1-555-123-4567',
    address: '123 Main Street',
    city: 'New York',
    state: 'NY',
    zipCode: '10001',
    country: 'USA',
    website: 'https://abcconstruction.com',
    industry: 'construction',
    companySize: '201-500',
    status: 'active',
    source: 'referral',
    rating: 4,
    estimatedValue: 5000000,
    notes: 'Very reliable client with consistent projects',
    createdAt: new Date('2024-01-15').toISOString(),
    updatedAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: '2',
    companyName: 'Premier Building Services',
    contactPerson: 'Sarah Johnson',
    email: 'contact@premierbuilding.com',
    phone: '+1-555-234-5678',
    address: '456 Oak Avenue',
    city: 'Los Angeles',
    state: 'CA',
    zipCode: '90210',
    country: 'USA',
    website: 'https://premierbuilding.com',
    industry: 'commercial',
    companySize: '51-200',
    status: 'lead',
    source: 'website',
    rating: 5,
    estimatedValue: 3500000,
    notes: 'Interested in commercial projects',
    createdAt: new Date('2024-01-20').toISOString(),
    updatedAt: new Date('2024-01-20').toISOString(),
  },
  {
    id: '3',
    companyName: 'Metro Infrastructure Ltd',
    contactPerson: 'Michael Davis',
    email: 'projects@metroinfra.com',
    phone: '+1-555-345-6789',
    address: '789 Pine Street',
    city: 'Chicago',
    state: 'IL',
    zipCode: '60601',
    country: 'USA',
    website: 'https://metroinfra.com',
    industry: 'infrastructure',
    companySize: '500+',
    status: 'opportunity',
    source: 'social_media',
    rating: 4,
    estimatedValue: 8000000,
    notes: 'Large infrastructure projects specialist',
    createdAt: new Date('2024-02-01').toISOString(),
    updatedAt: new Date('2024-02-01').toISOString(),
  },
  {
    id: '4',
    companyName: 'Green Home Builders',
    contactPerson: 'Lisa Wilson',
    email: 'hello@greenhomebuilders.com',
    phone: '+1-555-456-7890',
    address: '321 Elm Drive',
    city: 'Austin',
    state: 'TX',
    zipCode: '73301',
    country: 'USA',
    website: 'https://greenhomebuilders.com',
    industry: 'residential',
    companySize: '11-50',
    status: 'active',
    source: 'referral',
    rating: 5,
    estimatedValue: 2500000,
    notes: 'Specializes in eco-friendly residential construction',
    createdAt: new Date('2024-02-10').toISOString(),
    updatedAt: new Date('2024-02-10').toISOString(),
  },
  {
    id: '5',
    companyName: 'Urban Development Partners',
    contactPerson: 'Robert Brown',
    email: 'info@urbandevelopment.com',
    phone: '+1-555-567-8901',
    address: '654 Cedar Lane',
    city: 'Seattle',
    state: 'WA',
    zipCode: '98101',
    country: 'USA',
    website: 'https://urbandevelopment.com',
    industry: 'mixed_use',
    companySize: '201-500',
    status: 'inactive',
    source: 'cold_call',
    rating: 3,
    estimatedValue: 4200000,
    notes: 'Mixed-use development projects, currently on hold',
    createdAt: new Date('2024-02-15').toISOString(),
    updatedAt: new Date('2024-02-15').toISOString(),
  },
];

export const MOCK_CLIENT_STATS: ClientStats = {
  totalClients: MOCK_CLIENTS.length,
  activeClients: MOCK_CLIENTS.filter(c => c.status === 'active').length,
  leads: MOCK_CLIENTS.filter(c => c.status === 'lead').length,
  opportunities: MOCK_CLIENTS.filter(c => c.status === 'opportunity').length,
  inactiveClients: MOCK_CLIENTS.filter(c => c.status === 'inactive').length,
  lostClients: MOCK_CLIENTS.filter(c => c.status === 'lost').length,
  overdueFollowUps: 0,
  conversionRate: 65.5,
  averageRating: MOCK_CLIENTS.reduce((sum, c) => sum + (c.rating || 0), 0) / MOCK_CLIENTS.length,
  totalEstimatedValue: MOCK_CLIENTS.reduce((sum, c) => sum + (c.estimatedValue || 0), 0),
  clientsBySource: [
    { source: 'referral', count: MOCK_CLIENTS.filter(c => c.source === 'referral').length, percentage: 40 },
    { source: 'website', count: MOCK_CLIENTS.filter(c => c.source === 'website').length, percentage: 20 },
    { source: 'social_media', count: MOCK_CLIENTS.filter(c => c.source === 'social_media').length, percentage: 20 },
    { source: 'cold_call', count: MOCK_CLIENTS.filter(c => c.source === 'cold_call').length, percentage: 20 },
  ],
  clientsBySize: [
    { size: '1-10', count: 0, percentage: 0 },
    { size: '11-50', count: MOCK_CLIENTS.filter(c => c.companySize === '11-50').length, percentage: 20 },
    { size: '51-200', count: MOCK_CLIENTS.filter(c => c.companySize === '51-200').length, percentage: 20 },
    { size: '201-500', count: MOCK_CLIENTS.filter(c => c.companySize === '201-500').length, percentage: 40 },
    { size: '500+', count: MOCK_CLIENTS.filter(c => c.companySize === '500+').length, percentage: 20 },
  ],
  clientsByStatus: [
    { status: 'lead', count: MOCK_CLIENTS.filter(c => c.status === 'lead').length, percentage: 20 },
    { status: 'opportunity', count: MOCK_CLIENTS.filter(c => c.status === 'opportunity').length, percentage: 20 },
    { status: 'active', count: MOCK_CLIENTS.filter(c => c.status === 'active').length, percentage: 40 },
    { status: 'inactive', count: MOCK_CLIENTS.filter(c => c.status === 'inactive').length, percentage: 20 },
    { status: 'lost', count: MOCK_CLIENTS.filter(c => c.status === 'lost').length, percentage: 0 },
  ],
  clientsByLocation: [
    { location: 'New York', count: 1, percentage: 20 },
    { location: 'Los Angeles', count: 1, percentage: 20 },
    { location: 'Chicago', count: 1, percentage: 20 },
    { location: 'Austin', count: 1, percentage: 20 },
    { location: 'Seattle', count: 1, percentage: 20 },
  ],
  monthlyConversions: [
    { month: '2024-01', count: 2, value: 8500000 },
    { month: '2024-02', count: 3, value: 14700000 },
  ],
  recentActivities: [
    {
      id: '1',
      type: 'created',
      description: 'Client ABC Construction Corp was created',
      clientId: '1',
      clientName: 'ABC Construction Corp',
      userId: '1',
      userName: 'Test User',
      timestamp: new Date('2024-01-15').toISOString(),
    },
    {
      id: '2',
      type: 'status_changed',
      description: 'Client status changed to Active',
      clientId: '2',
      clientName: 'Premier Building Services',
      userId: '1',
      userName: 'Test User',
      timestamp: new Date('2024-02-01').toISOString(),
    },
  ],
};